namespace Breeze.Sharp {
  /// <summary>
  /// AutoGeneratedKeyType is an enum containing all of the valid states for an automatically generated key.
  /// </summary>
  public enum AutoGeneratedKeyType {
    None = 0,
    Identity = 1,
    KeyGenerator = 2
  }
}
